### ISSUE TITLE
Why css to set the size of the picture, no effect? The problem is serious.

### ISSUE THREAD

**Issue by harrydengchao** [atwxp/v-qrcode#1]
Why css to set the size of the picture, no effect? The problem is serious.

**Comment by atwxp** [comment]
The v-qrcode component use [qrious](https://github.com/neocotic/qrious/blob/master/) internally,  it has two renders [ImageRenderer.js](https://github.com/neocotic/qrious/blob/master/src/renderer/ImageRenderer.js) and [CanvasRenderer.js](https://github.com/neocotic/qrious/blob/master/src/renderer/CanvasRenderer.js).

The part of code inside `ImageRenderer.js`(CanvasRenderer is almost the same as ImageRenderer):

```
resize() {
    const qrious = this.qrious
    const image = qrious.image

    image.width = qrious.size
    image.height = qrious.size
}
```
You can see  the `size option` used in v-qrcode actually is passed to `qrious.size` which is used for setting the size of qrcode, in the image render context, it' s `img element`.

In v-qrcode component , I just wrapper this img element in a div, see [here](https://github.com/atwxp/v-qrcode/blob/master/src/index.vue#L91), no other css/js control any more.

```
<template>
    <div v-bind:class="cls"></div>
</template>

this.$el.appendChild(qr[this.type])
```

So the real size of qrcode is determined by `size option`, set css to the qrcode's wrapper has no effect.

Hope to help you, Thx!

**Comment by harrydengchao** [comment]
@atwxp Hi
It is only possible to set the size in advance in the configuration. For different dpr screen, I want to control the size of img in scss. Because I need to set the size of the viewport, to dynamically set. However, when I set the scss, and did not take effect. I do not know why

**Comment by atwxp** [comment]
may be you should set the size of img, but not img's wrapper
```
div > img {
    width: @w;
    height: @h;
}
```

**Comment by harrydengchao** [comment]
@atwxp Hi
Yes, I wrote that way. But did not compile out.
---
as follows:

![image](https://cloud.githubusercontent.com/assets/13941171/23578624/91076818-0116-11e7-9504-2052560f2251.png)

![image](https://cloud.githubusercontent.com/assets/13941171/23578666/58381126-0117-11e7-87ac-fc0c837c9cd8.png)

**Comment by atwxp** [comment]
Here is a [demo - jsbin](http://output.jsbin.com/robakasuci), It's ok. 
So is there something wrong with your css?

**Comment by harrydengchao** [comment]
@atwxp 
In the picture. I wrote the css has not been compiled out, chrome tools which did not see

**Comment by atwxp** [comment]
see [demo](http://output.jsbin.com/robakasuci) wheather it works nor not. If ok, then no problem.

you can modify your code as simple as possible, then add other code step by step, may be the build tool cause error.

**Comment by harrydengchao** [comment]
May be caused by the build tool.
Thank you
