### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by dprothero** [atwxp/v-qrcode#2]
I'm seeing this error in the console and not getting a rendered QR code:
```
[Vue warn]: Failed to mount component: template or render function not defined. 
(found in <Qrcode>)
```

Here's a repro:
https://github.com/dprothero/vue-basics/tree/v-qrcode-issue-2

**Comment by dprothero** [comment]
UPDATE: Strangely, I can manually copy the index.vue from this project into my project and use it that way just fine.

**Comment by atwxp** [comment]
```js
// es5
const Qrcode = require('v-qrcode').qrcode;
```

**Comment by dprothero** [comment]
Thanks for the help!
